# comprehensive github action yml reference: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions

---
name: CI

on:
  push: # any push event to master will trigger this
    branches: ["main"]
  pull_request: # any pull request to master will trigger this
    branches: ["main"]
  workflow_dispatch: # allows you to manually trigger run

jobs:
  tests:
    name: Run
    runs-on: ubuntu-latest # for all available VM runtime, see this: https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners

#    container:
#      image: node:19
#
#    services:
#      selenium:
#        image: selenium/standalone-chrome
#        options: --shm-size=2gb

    steps:
      - uses: "actions/checkout@v3" # https://github.com/marketplace/actions/checkout
      - uses: "actions/setup-python@v4" # https://github.com/marketplace/actions/setup-python
        with:
          python-version: "${{ matrix.python-version }}"
#      - uses: actions/setup-node@v3
#        with:
#          node-version: "19"
#          cache: "npm"

      - name: "Install dependencies on MacOS or Linux"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel virtualenv
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pip install .
      - name: "Run"
        run: |
          python debug/test_selenium.py
